import { NodeData, EdgeData } from "./types";

// ─────────────────────────────────────────────────────────────
// PRESET 1: End-to-End Master System Flowchart (10 Nodes)
// ─────────────────────────────────────────────────────────────
export const e2eNodes: NodeData[] = [
  {
    id: "pdf-source",
    x: 30,
    y: 190,
    w: 170,
    h: 90,
    type: "source",
    stageNumber: 1,
    stageName: "Multi-Modal Ingestion",
    category: "INGESTION SOURCE",
    name: "Research PDF Source",
    subtitle: "Unstructured Literature",
    file: "papers/sample_papers/[1-48].pdf",
    icon: "file",
    color: "#DA7756",
    inputs: ["Academic PDF Papers [1..48]"],
    outputs: ["Raw Binary Stream", "Embedded Fonts"],
    details: "Scientific paper corpus spanning 48 diverse machine learning architectures, multimodal transformers, and arXiv preprints.",
    metrics: "48 Papers Ingested",
    tech: ["arXiv", "PDF 1.7 Spec", "Local Corpus"],
  },
  {
    id: "tri-parser",
    x: 240,
    y: 190,
    w: 180,
    h: 90,
    type: "process",
    stageNumber: 1,
    stageName: "Multi-Modal Ingestion",
    category: "TRI-PARSER ROUTER",
    name: "Extraction Router",
    subtitle: "PyMuPDF + GROBID + Docling",
    file: "backend/app/extraction/router.py",
    icon: "workflow",
    color: "#DA7756",
    inputs: ["Raw Binary Stream"],
    outputs: ["Bounding Boxes", "TEI-XML Tree", "LaTeX Formulas"],
    details: "Cascading router intelligently delegating multi-column text to PyMuPDF, bibliographic metadata to GROBID TEI-XML, and tables to IBM Docling.",
    metrics: "< 850ms / paper",
    tech: ["PyMuPDF", "GROBID", "IBM Docling", "LayoutLM"],
  },
  {
    id: "canonical-gate",
    x: 460,
    y: 190,
    w: 180,
    h: 90,
    type: "decision",
    stageNumber: 1,
    stageName: "Multi-Modal Ingestion",
    category: "SCHEMA QA GATE",
    name: "Canonical Schema QA Gate",
    subtitle: "Merger & Quality Auditor",
    file: "backend/app/extraction/merger.py",
    icon: "layers",
    color: "#DA7756",
    inputs: ["Multi-engine Text & Table streams"],
    outputs: ["CanonicalPaperDocument Schema"],
    details: "Reconciles parser overlaps into a single canonical document schema. Validates completeness with 0 missing attributes.",
    metrics: "100% Pass Rate",
    tech: ["CanonicalPaperDocument", "ConflictMerger", "Pydantic v2"],
  },
  {
    id: "vector-rag",
    x: 680,
    y: 70,
    w: 180,
    h: 90,
    type: "storage",
    stageNumber: 2,
    stageName: "Memory & Knowledge",
    category: "SEMANTIC MEMORY",
    name: "Flat-File Vector RAG",
    subtitle: "FAISS Cosine Similarity Index",
    file: "backend/app/retrieval/vector_db.py",
    icon: "database",
    color: "#38BDF8",
    inputs: ["Canonical Sections Chunks"],
    outputs: ["Top-3 Semantic Embeddings"],
    details: "Zero-cloud FAISS vector store persisting dense semantic embeddings directly on disk for sub-millisecond retrieval.",
    metrics: "0ms Cloud Latency",
    tech: ["FAISS IndexFlatIP", "SentenceTransformers", "rag_embeddings/"],
  },
  {
    id: "kg-graph",
    x: 680,
    y: 310,
    w: 180,
    h: 90,
    type: "storage",
    stageNumber: 2,
    stageName: "Memory & Knowledge",
    category: "KNOWLEDGE MESH",
    name: "NetworkX Knowledge Graph",
    subtitle: "Bipartite Entity-Relation Graph",
    file: "backend/app/retrieval/knowledge_graph.py",
    icon: "workflow",
    color: "#38BDF8",
    inputs: ["Extracted Math Entities & Symbols"],
    outputs: ["USES / OPTIMIZES Triples"],
    details: "Topological graph connecting mathematical variables directly to target hyperparameters, datasets, and PyTorch modules.",
    metrics: "1,200+ Nodes Indexed",
    tech: ["NetworkX 3.2", "Graph Triples", "knowledge_graphs/"],
  },
  {
    id: "reasoning-mesh",
    x: 900,
    y: 180,
    w: 190,
    h: 110,
    type: "process",
    stageNumber: 3,
    stageName: "Reasoning Mesh",
    category: "AGENTIC REASONING",
    name: "Reasoning Mesh (8 Agents)",
    subtitle: "Decomp + Feas + Sequencing",
    file: "backend/app/agents/orchestrator.py",
    icon: "cpu",
    color: "#A855F7",
    inputs: ["Canonical Document", "Vector RAG", "Knowledge Graph"],
    outputs: ["ComponentGraph", "Milestone DAG (M1..M5)"],
    details: "Autonomous multi-agent cluster: DecompositionAgent creates sub-components; FeasibilityAgent profiles VRAM; SequencingAgent orders DAG milestones.",
    metrics: "8 Coordinated Agents",
    tech: ["LangGraph", "LangChain Core", "CUDA Memory Profiler"],
  },
  {
    id: "dual-code",
    x: 1130,
    y: 70,
    w: 180,
    h: 90,
    type: "process",
    stageNumber: 4,
    stageName: "Synthesis & Verification",
    category: "SYNTHESIS ENGINE",
    name: "Dual Code Engine",
    subtitle: "Gemini 2.5 + Qwen 2.5 Coder",
    file: "backend/app/core/dual_code_engine.py",
    icon: "code",
    color: "#34D399",
    inputs: ["Milestone DAG", "LaTeX Mathematical Spec"],
    outputs: ["8-File PyTorch Package (332 Files)"],
    details: "Splits synthesis between Gemini 2.5 Flash (mathematical derivations) and Qwen 2.5 Coder 32B (idiomatic PyTorch module code).",
    metrics: "332 Files Synthesized",
    tech: ["DualCodeEngine", "Qwen 2.5 Coder 32B", "Gemini 2.5 Flash"],
  },
  {
    id: "ast-gate",
    x: 1130,
    y: 310,
    w: 180,
    h: 90,
    type: "verify",
    stageNumber: 4,
    stageName: "Synthesis & Verification",
    category: "VIRTUAL VERIFIER",
    name: "3-Layer Virtual AST Gate",
    subtitle: "ast.parse + Security + Mock Tensor",
    file: "backend/app/core/code_verifier.py",
    icon: "shield",
    color: "#34D399",
    inputs: ["Generated PyTorch .py Scripts"],
    outputs: ["100% AST Syntax Certificate"],
    details: "Tri-layer gate executing Python AST syntax parsing, security blacklisting (os.system/subprocess), and dummy tensor forward-passes.",
    metrics: "100% AST Pass Rate",
    tech: ["ast.parse", "Security Blacklist", "Mock Tensor Runner"],
  },
  {
    id: "win32-dock",
    x: 1350,
    y: 70,
    w: 175,
    h: 90,
    type: "terminal",
    stageNumber: 5,
    stageName: "Desktop & Mascot Sync",
    category: "OS INTEGRATION",
    name: "Win32 C-FFI Taskbar Dock",
    subtitle: "Koffi Shell32.dll Interop",
    file: "frontend/electron_app/src/main.js",
    icon: "monitor",
    color: "#EC4899",
    inputs: ["FastAPI SSE Events", "Display WorkArea"],
    outputs: ["Shell_TrayWnd Snapping", "Lockstep Drag"],
    details: "Native Windows C-FFI call to SHAppBarMessage detecting physical taskbar bounds, docking the app with zero desktop disruption.",
    metrics: "0ms Polling Overhead",
    tech: ["koffi (C-FFI)", "Shell32.dll", "Electron 34"],
  },
  {
    id: "mascot-fsm",
    x: 1350,
    y: 310,
    w: 175,
    h: 90,
    type: "terminal",
    stageNumber: 5,
    stageName: "Desktop & Mascot Sync",
    category: "STATE REFLECTION",
    name: "13-State Mascot FSM",
    subtitle: "60FPS HTML5 Canvas Engine",
    file: "frontend/electron_app/src/mascot.js",
    icon: "sparkles",
    color: "#EC4899",
    inputs: ["Pipeline State Stream"],
    outputs: ["Real-Time Companion Emotion"],
    details: "Renders 4 academic characters across 13 states (thinking, excited, sipping coffee, angry upon AST error) matching backend execution.",
    metrics: "60 FPS Sprite Sync",
    tech: ["Canvas 2D API", "13-State FSM", "Web Audio API"],
  },
];

export const e2eEdges: EdgeData[] = [
  { id: "e1", from: "pdf-source", to: "tri-parser", label: "PDF Byte Stream", color: "#DA7756" },
  { id: "e2", from: "tri-parser", to: "canonical-gate", label: "Multi-Engine Streams", color: "#DA7756" },
  { id: "e3", from: "canonical-gate", to: "vector-rag", label: "Chunk Embeddings", color: "#38BDF8" },
  { id: "e4", from: "canonical-gate", to: "kg-graph", label: "Math Triples", color: "#38BDF8" },
  { id: "e5", from: "vector-rag", to: "reasoning-mesh", label: "Semantic Context", color: "#38BDF8" },
  { id: "e6", from: "kg-graph", to: "reasoning-mesh", label: "Entity Relations", color: "#38BDF8" },
  { id: "e7", from: "reasoning-mesh", to: "dual-code", label: "Milestone DAG (M1..M5)", color: "#A855F7" },
  { id: "e8", from: "dual-code", to: "ast-gate", label: "PyTorch Code Package", color: "#34D399" },
  { id: "e9", from: "ast-gate", to: "win32-dock", label: "Execution Success SSE", color: "#EC4899" },
  { id: "e10", from: "ast-gate", to: "mascot-fsm", label: "FSM State: excite", color: "#EC4899" },
];

// ─────────────────────────────────────────────────────────────
// PRESET 2: LangGraph 5-Node Acyclic StateGraph
// ─────────────────────────────────────────────────────────────
export const langgraphNodes: NodeData[] = [
  {
    id: "lg-1",
    x: 50,
    y: 200,
    w: 190,
    h: 100,
    type: "process",
    stageNumber: 1,
    stageName: "Ingestion Node",
    category: "LANGGRAPH NODE 1",
    name: "1. ingestion_node",
    subtitle: "Tri-Parser & FAISS Embedder",
    file: "backend/app/graph/nodes/ingestion.py",
    icon: "file",
    color: "#DA7756",
    inputs: ["Uploaded PDF Path"],
    outputs: ["CanonicalPaperDocument", "FAISS Vector DB"],
    details: "Parses academic PDF, standardizes sections into canonical schema, indexes text chunks into FAISS vector database and NetworkX knowledge graph.",
    metrics: "< 1.2s execution",
    tech: ["ExtractionRouter", "FAISS", "NetworkX", "Pydantic"],
  },
  {
    id: "lg-2",
    x: 290,
    y: 200,
    w: 190,
    h: 100,
    type: "process",
    stageNumber: 2,
    stageName: "Extraction Node",
    category: "LANGGRAPH NODE 2",
    name: "2. extraction_node",
    subtitle: "Decomposition & Parameters",
    file: "backend/app/graph/nodes/extraction.py",
    icon: "cpu",
    color: "#38BDF8",
    inputs: ["Canonical Document"],
    outputs: ["ComponentGraph", "Hyperparameter Dict"],
    details: "Extracts sub-modules (encoders, decoders, attention heads) and compiles hyperparameters (learning rate, weight decay, hidden dims).",
    metrics: "0 missing params",
    tech: ["DecompositionAgent", "ParameterAgent", "Regex"],
  },
  {
    id: "lg-3",
    x: 530,
    y: 200,
    w: 190,
    h: 100,
    type: "process",
    stageNumber: 3,
    stageName: "Feasibility Node",
    category: "LANGGRAPH NODE 3",
    name: "3. feasibility_node",
    subtitle: "VRAM Scaling & Gap Audit",
    file: "backend/app/graph/nodes/feasibility.py",
    icon: "shield",
    color: "#A855F7",
    inputs: ["Extracted Parameters", "Host GPU Specs"],
    outputs: ["FeasibilityReport", "Resolved Gaps"],
    details: "Simulates parameter memory footprints across batch sizes. Flags VRAM bottlenecks for local GPUs and injects unstated paper defaults.",
    metrics: "CUDA Profile Verified",
    tech: ["FeasibilityAgent", "GapAgent", "FLOPs Profiler"],
  },
  {
    id: "lg-4",
    x: 770,
    y: 200,
    w: 190,
    h: 100,
    type: "process",
    stageNumber: 4,
    stageName: "Sequencing Node",
    category: "LANGGRAPH NODE 4",
    name: "4. sequencing_node",
    subtitle: "Milestone DAG & Tech Spec",
    file: "backend/app/graph/nodes/sequencing.py",
    icon: "workflow",
    color: "#34D399",
    inputs: ["ComponentGraph", "Resolved Parameters"],
    outputs: ["Milestone DAG (M1..M5)", "Code Blueprint"],
    details: "Generates structured 5-milestone implementation plan: 1. Dataset, 2. Modules, 3. Assembly, 4. Loss, 5. Training Loop.",
    metrics: "5 Structured Milestones",
    tech: ["SequencingAgent", "SpecificationAgent", "DAG Planner"],
  },
  {
    id: "lg-5",
    x: 1010,
    y: 200,
    w: 190,
    h: 100,
    type: "verify",
    stageNumber: 5,
    stageName: "Verification Node",
    category: "LANGGRAPH NODE 5",
    name: "5. verification_node",
    subtitle: "Dual Code & 3-Layer AST Gate",
    file: "backend/app/graph/nodes/verification.py",
    icon: "code",
    color: "#EC4899",
    inputs: ["Milestone DAG", "Technical Spec"],
    outputs: ["Verified PyTorch Package (8 Files)"],
    details: "Dual-model PyTorch generation with automated ast.parse validation, security import blacklist audit, and tensor shape verification.",
    metrics: "100% AST Passed",
    tech: ["DualCodeEngine", "ast.parse", "CodeVerifier"],
  },
];

export const langgraphEdges: EdgeData[] = [
  { id: "lg-e1", from: "lg-1", to: "lg-2", label: "Canonical Doc", color: "#DA7756" },
  { id: "lg-e2", from: "lg-2", to: "lg-3", label: "Component Graph", color: "#38BDF8" },
  { id: "lg-e3", from: "lg-3", to: "lg-4", label: "Feasibility Report", color: "#A855F7" },
  { id: "lg-e4", from: "lg-4", to: "lg-5", label: "Milestone DAG", color: "#34D399" },
  { id: "lg-e5", from: "lg-5", to: "lg-4", label: "Retry on AST Error (Self-Heal Loop)", style: "dashed", color: "#EF4444" },
];

// ─────────────────────────────────────────────────────────────
// PRESET 3: Dual Code Engine & 3-Layer AST Gate Deep-Dive
// ─────────────────────────────────────────────────────────────
export const astGateNodes: NodeData[] = [
  {
    id: "ag-dag",
    x: 50,
    y: 190,
    w: 200,
    h: 90,
    type: "source",
    stageNumber: 1,
    stageName: "Milestone DAG Spec",
    category: "SPECIFICATION SPEC",
    name: "Milestone Build DAG",
    subtitle: "M1..M5 Implementation Plan",
    file: "backend/app/agents/specification_agent.py",
    icon: "workflow",
    color: "#DA7756",
    inputs: ["Sequenced Components"],
    outputs: ["Layer Dimensions", "Tensor Signatures"],
    details: "Formal specifications detailing exact tensor shapes, forward-pass signatures, and loss functions for all PyTorch files.",
    metrics: "5 Milestones Ordered",
    tech: ["SpecificationAgent", "DAG Planner"],
  },
  {
    id: "ag-gemini",
    x: 320,
    y: 80,
    w: 210,
    h: 90,
    type: "process",
    stageNumber: 2,
    stageName: "Parallel Synthesis",
    category: "MATH REASONING MODEL",
    name: "Google Gemini 2.5 Flash",
    subtitle: "Formula & Context Derivation",
    file: "backend/app/core/dual_code_engine.py",
    icon: "cpu",
    color: "#38BDF8",
    inputs: ["LaTeX Equations", "Theoretical Context"],
    outputs: ["Mathematical Algorithms in PyTorch"],
    details: "Solves tensor dimension alignment, non-standard loss gradients, and attention mechanism formulas with long context window.",
    metrics: "1M Token Window",
    tech: ["Gemini 2.5 Flash", "Google GenAI SDK"],
  },
  {
    id: "ag-qwen",
    x: 320,
    y: 300,
    w: 210,
    h: 90,
    type: "process",
    stageNumber: 2,
    stageName: "Parallel Synthesis",
    category: "IDIOMATIC CODE MODEL",
    name: "Qwen 2.5 Coder 32B",
    subtitle: "High-Throughput PyTorch Generator",
    file: "backend/app/core/dual_code_engine.py",
    icon: "code",
    color: "#A855F7",
    inputs: ["Target File Skeleton", "Milestone Spec"],
    outputs: ["Idiomatic nn.Module Implementations"],
    details: "Synthesizes modular PyTorch code adhering strictly to PEP-8, type hints, docstrings, and device-agnostic execution.",
    metrics: "32B Parameters",
    tech: ["Qwen 2.5 Coder", "Hugging Face / Local"],
  },
  {
    id: "ag-ast1",
    x: 600,
    y: 190,
    w: 190,
    h: 90,
    type: "verify",
    stageNumber: 3,
    stageName: "Syntax Tree Gate",
    category: "LAYER 1 AUDIT",
    name: "ast.parse Syntax Gate",
    subtitle: "Python Abstract Syntax Tree",
    file: "backend/app/core/code_verifier.py",
    icon: "shield",
    color: "#34D399",
    inputs: ["Raw Generated .py Files"],
    outputs: ["Syntax Conformance Token"],
    details: "Parses Python code into an Abstract Syntax Tree without executing it, catching syntax errors, invalid indentation, or unclosed brackets.",
    metrics: "100% AST Conformance",
    tech: ["Python ast", "SyntaxTree Parser"],
  },
  {
    id: "ag-ast2",
    x: 840,
    y: 190,
    w: 190,
    h: 90,
    type: "verify",
    stageNumber: 4,
    stageName: "Security Sandbox",
    category: "LAYER 2 AUDIT",
    name: "Security Import Scanner",
    subtitle: "Host Sandbox Isolation",
    file: "backend/app/core/code_verifier.py",
    icon: "shield",
    color: "#34D399",
    inputs: ["Parsed AST Nodes"],
    outputs: ["Security Sanitized Code"],
    details: "Inspects AST imports, immediately blocking dangerous modules like os.system, subprocess, socket, or eval to safeguard host machine.",
    metrics: "0 Exploits Permitted",
    tech: ["AST NodeVisitor", "Import Blacklist"],
  },
  {
    id: "ag-ast3",
    x: 1080,
    y: 190,
    w: 190,
    h: 90,
    type: "verify",
    stageNumber: 5,
    stageName: "Tensor Simulation",
    category: "LAYER 3 AUDIT",
    name: "Mock Tensor Simulator",
    subtitle: "Virtual Forward-Pass Gate",
    file: "backend/app/core/code_verifier.py",
    icon: "check",
    color: "#34D399",
    inputs: ["Sanitized PyTorch Modules"],
    outputs: ["Runnable Verified PyTorch Package"],
    details: "Feeds synthetic mock tensors through model.forward(x) to mathematically prove tensor dimension consistency across layers.",
    metrics: "Zero Dimension Mismatch",
    tech: ["torch.randn", "Mock Forward Pass"],
  },
];

export const astGateEdges: EdgeData[] = [
  { id: "ag-e1", from: "ag-dag", to: "ag-gemini", label: "LaTeX Equations", color: "#38BDF8" },
  { id: "ag-e2", from: "ag-dag", to: "ag-qwen", label: "Module Skeletons", color: "#A855F7" },
  { id: "ag-e3", from: "ag-gemini", to: "ag-ast1", label: "Algorithmic Code", color: "#38BDF8" },
  { id: "ag-e4", from: "ag-qwen", to: "ag-ast1", label: "PyTorch Module Code", color: "#A855F7" },
  { id: "ag-e5", from: "ag-ast1", to: "ag-ast2", label: "Syntax Verified", color: "#34D399" },
  { id: "ag-e6", from: "ag-ast2", to: "ag-ast3", label: "Security Cleared", color: "#34D399" },
];
